export const VEHICAL_ASSIGNED_DETAILS = "VEHICAL_ASSIGNED_DETAILS";
export const VEHICAL_SERVICE_APPROVAL = "VEHICAL_SERVICE_APPROVAL";
export const ASSINGE_ENGINEER = "ASSINGE_ENGINEER";
export const MAINTENANCE_ENGG_LIST = "MAINTENANCE_ENGG_LIST";
export const SERVICE_APPROVAL_STATUS = "SERVICE_APPROVAL_STATUS";