export const UPDATE_VEHICLE_STATUS = "UPDATE_VEHICLE_STATUS";
export const GET_ROUTINESERVICE_LIST = "GET_ROUTINESERVICE_LIST";
export const GET_LABOURCHARGE_LIST = "GET_LABOURCHARGE_LIST";
export const GET_SPAREPARTS_LIST = "GET_SPAREPARTS_LIST";
export const GET_ROUTINESERVICE_PRICE_LIST = "GET_ROUTINESERVICE_PRICE_LIST";
export const GET_LABOURCHARGES_PRICE_LIST = "GET_LABOURCHARGES_PRICE_LIST";

