export const VEHICLE_STATUS_DETAILS = "VEHICLE_STATUS_DETAILS";
export const GET_VEHICLE_STATUS_DETAILS = "GET_VEHICLE_STATUS_DETAILS";
export const GET_VEHICLE_STATUS_LIST = "GET_VEHICLE_STATUS_LIST";

